services:
  chat_server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    container_name: chat_server
    environment:
      SUPERUSER_USERNAME: "admin"
      SUPERUSER_PASSWORD: "admin"

      POSTGRES_USER: "changethis"
      POSTGRES_PASSWORD: "changethis"
      POSTGRES_HOST: "changethis"
      POSTGRES_PORT: "changethis"
      POSTGRES_DB: "changethis"

      # Server configuration
      HOST: 0.0.0.0
      PORT: 8000
      # CHANGE THIS
      SECRET_KEY: "your-secret-key-change-this-in-production"
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat_network
networks:
  chat_network:
    driver: bridge
